name: Publish .NET libraries / packages

on:
  workflow_dispatch:
  push:
    branches:
      - main # or the branch you want to trigger the action

permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    working-directory: ./src/HeaderFooter

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      Version: ${{ steps.determine_version.outputs.Version }}
      CommitsSinceVersionSource: ${{ steps.determine_version.outputs.CommitsSinceVersionSource }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch-depth is needed for GitVersion

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # Use the appropriate .NET version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.12
        with:
          versionSpec: 5.x

      - name: Determine Version
        id: determine_version
        uses: gittools/actions/gitversion/execute@v0.9.12

      - name: Save GitVersion outputs
        id: save_version
        run: |
          echo "Version=${{ steps.determine_version.outputs.SemVer }}" >> $GITHUB_ENV
          echo "CommitsSinceVersionSource=${{ steps.determine_version.outputs.CommitsSinceVersionSource }}" >> $GITHUB_ENV
        outputs:
          Version: ${{ steps.determine_version.outputs.SemVer }}
          CommitsSinceVersionSource: ${{ steps.determine_version.outputs.CommitsSinceVersionSource }}

      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ env.Version }}"
          echo "CommitsSinceVersionSource: ${{ env.CommitsSinceVersionSource }}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack --configuration Release --no-restore -p:Version='${{ env.Version }}'

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nugetPackage
          path: "**/*.nupkg"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # only run job if on the main branch

    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          name: nugetPackage

      - name: Prep packages
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name gHTechSkillzAcademy "https://nuget.pkg.github.com/ViswanathaSwamy-PK-TechSkillz-Academy/index.json"

      - name: Push package to GitHub packages
        if: needs.build.outputs.CommitsSinceVersionSource > 0 # Only release if there has been a commit/version change
        run: dotnet nuget push '**/*.nupkg' --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "gHTechSkillzAcademy"

      - name: Create Release
        if: needs.build.outputs.CommitsSinceVersionSource > 0 # Only release if there has been a commit/version change
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.Version }}
          name: Release ${{ needs.build.outputs.Version }}
          artifacts: "nugetPackage/*"
          token: ${{ secrets.GHUB_PAT }}
