# GitHub Actions workflow to publish .NET 8 library to GitHub Packages

name: Publish .NET package

on:
  workflow_dispatch:
  push:
    branches:
      - main # or the branch you want to trigger the action

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    working-directory: ./src/HeaderFooter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # Use the appropriate .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack --configuration Release --no-restore

      - name: Publish to GitHub Packages
        run: dotnet nuget push '**/*.nupkg' --source 'github'
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
